### ISSUE TITLE
Error: unhandled exception: cannot open: glfw/src/x11_init.c [IOError] when defined static compilation

### ISSUE THREAD

**Issue by Wh1teDuke** [johnnovak/nim-glfw#1]
Tested on Linux.
**Solution**: remove 'glfw/' from `compile` statements.

https://github.com/johnnovak/nim-glfw/blob/master/glfw/wrapper.nim#L19

**Comment by johnnovak** [comment]
I don't (can't) test on Linux. Can you create a PR?

**Comment by Wh1teDuke** [comment]
Sure.

**Comment by johnnovak** [comment]
@Wh1teDuke Closing this, please raise the PR and I'll merge it in.
