### ISSUE TITLE
Example: Triangle => Error: unhandled exception: GLX: Failed to create context: GLXBadFBConfig [GLFWError]

### ISSUE THREAD

**Issue by rtdietrich** [johnnovak/nim-glfw#3]
When I try to start the example "Triangle" I always get the error message: "Error: unhandled exception: GLX: Failed to create context: GLXBadFBConfig [GLFWError]".

All other sample codes work cleanly without problems.

My system:
Virtualbox: Linux/Manjaro; GLFW X11; Nim1.6 using VSCode

**Comment by johnnovak** [comment]
Sorry, I can't test this on Linux, only on Windows and OS X. Do any of the other examples work?
