### ISSUE TITLE
Reasoning for skiped examples directory when using nimble

### ISSUE THREAD

**Issue by ParticlePeter** [johnnovak/nim-glfw#4]
Wondering why nimble excludes the examples directory (me new to nim, I assume this nimble statement is responsible:
`skipDirs = @["examples"]`). What is the reasoning for that?
You mention
>The best way to install the latest version of the package is via `nimble`

and then refer to the examples multiple times, which are omitted ... on purpose?

Cheers, PP

**Comment by johnnovak** [comment]
Well yes, that's on purpose. The idea is if you just install it as a dependency, you don't want anything else but the library code.

If you want to run the examples, just clone the repo.
